STADIUM_COORDS = {
    "jamsil":        (37.5121, 127.0722),
    "gocheok":       (37.4981, 126.8672),
    "suwon":         (37.2968, 127.0066),
    "incheon":       (37.4374, 126.6933),
    "daegu":         (35.8409, 128.6814),
    "busan":         (35.1940, 129.0609),
    "gwangju":       (35.1681, 126.8892),
    "daejeon":       (36.3166, 127.4267),
    "changwon":      (35.2244, 128.5822),
    "ulsan":         (35.5384, 129.2753),
    "icheon_lg":     (37.2721, 127.4420),
    "icheon_doosan": (37.2800, 127.4500),
    "gyeongsan":     (35.8209, 128.7378),
    "cheongju":      (36.6424, 127.4890),
    "goyang":        (37.6583, 126.8320),
}

STADIUMS = {
    # ── 1군 구장 ─────────────────────────────────────────────────
    "jamsil": {
        "id": "jamsil", "tier": "1군",
        "name": "잠실야구장",
        "teams": "두산 베어스 · LG 트윈스",
        "address": "서울 송파구 올림픽로 19-2",
        "subway": "2호선 잠실역 5번 출구 도보 5분",
        "capacity": 26100,
        "color": "#003087", "emoji": "🔵",
        "tip": "외야 응원석은 양 팀 팬 분위기가 완전히 달라요. 1루 응원석(LG), 3루 응원석(두산)으로 나뉘어요.",
        "sections": [
            {"name": "테이블석",    "zone": "premium", "price": "60,000~100,000", "view": 5, "rec": True,  "desc": "최고급 시야, 식음료 서비스 포함"},
            {"name": "내야 1층",    "zone": "inner",   "price": "15,000~20,000", "view": 5, "rec": True,  "desc": "경기 몰입감 최고, 타자 타구 방향 잘 보임"},
            {"name": "내야 2층",    "zone": "upper",   "price": "12,000~15,000", "view": 4, "rec": True,  "desc": "전체 경기 흐름 파악하기 좋음"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "10,000~12,000", "view": 3, "rec": False, "desc": "응원 분위기 최고, 시야는 좁음"},
            {"name": "외야 일반석", "zone": "outer",   "price": "8,000~10,000",  "view": 3, "rec": False, "desc": "저렴하지만 외야 깊숙이 앉으면 시야 제한"},
        ],
        "best_seats": [
            {"title": "혼자 or 커플 관람", "seat": "내야 1층 1루 측", "reason": "타자 정면으로 보여 투구 궤적이 가장 잘 보여요."},
            {"title": "가족 단체 관람",    "seat": "내야 2층 중앙",   "reason": "전체 경기장 한눈에 보이고 아이들이 안전해요."},
            {"title": "응원 즐기기",       "seat": "외야 응원석",     "reason": "응원단과 함께 노래·구호 최대치로 즐길 수 있어요."},
            {"title": "가성비 관람",       "seat": "외야 일반석",     "reason": "8천원에 KBO 라이브 경험 가능, 맥주 한 잔이면 충분."},
        ],
    },
    "gocheok": {
        "id": "gocheok", "tier": "1군",
        "name": "고척스카이돔",
        "teams": "키움 히어로즈",
        "address": "서울 구로구 경인로 430",
        "subway": "1호선 구일역 도보 5분",
        "capacity": 16000,
        "color": "#ff6600", "emoji": "🟠",
        "tip": "국내 유일 돔구장이라 우천 취소 없어요. 여름엔 에어컨, 겨울엔 히터 가동!",
        "sections": [
            {"name": "스카이박스",  "zone": "premium", "price": "200,000~",       "view": 5, "rec": False, "desc": "완전 프라이빗, 케이터링 서비스"},
            {"name": "테이블석",    "zone": "premium", "price": "50,000~80,000",  "view": 5, "rec": True,  "desc": "홈플레이트 주변 최고 시야"},
            {"name": "내야 1층",    "zone": "inner",   "price": "15,000~18,000",  "view": 5, "rec": True,  "desc": "돔 특유의 박진감, 소리 울림 좋음"},
            {"name": "내야 2층",    "zone": "upper",   "price": "12,000~15,000",  "view": 4, "rec": True,  "desc": "돔 전체 조망, 날씨 영향 없음"},
            {"name": "외야석",      "zone": "outer",   "price": "8,000~10,000",   "view": 3, "rec": False, "desc": "응원 분위기 뜨겁지만 시야 좁음"},
        ],
        "best_seats": [
            {"title": "처음 직관",       "seat": "내야 1층 홈플레이트 근처", "reason": "돔 구장 특유의 웅장한 느낌을 가장 잘 살릴 수 있어요."},
            {"title": "커플 데이트",     "seat": "테이블석",                 "reason": "음식 먹으면서 여유롭게 경기 관람 가능."},
            {"title": "비·더위 피하기", "seat": "어디든 OK",                "reason": "돔이라 날씨 상관없이 쾌적해요!"},
        ],
    },
    "suwon": {
        "id": "suwon", "tier": "1군",
        "name": "수원KT위즈파크",
        "teams": "KT 위즈",
        "address": "경기 수원시 장안구 경수대로 893",
        "subway": "1호선 수원역 → 버스 이동",
        "capacity": 20000,
        "color": "#c8102e", "emoji": "🔴",
        "tip": "주차장이 넓어서 자가용 이용이 편리해요. 경기 전 근처 수원왕갈비 먹는 것 추천!",
        "sections": [
            {"name": "프리미엄석",  "zone": "premium", "price": "50,000~",       "view": 5, "rec": True,  "desc": "홈플레이트 근처 최고의 시야"},
            {"name": "내야 1층",    "zone": "inner",   "price": "13,000~17,000", "view": 5, "rec": True,  "desc": "타자 정면, 투구 궤적 잘 보임"},
            {"name": "내야 2층",    "zone": "upper",   "price": "10,000~13,000", "view": 4, "rec": True,  "desc": "전체 경기 한눈에 조망"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "7,000~9,000",   "view": 3, "rec": False, "desc": "KT 위즈 열정 응원단"},
            {"name": "외야 일반석", "zone": "outer",   "price": "7,000~8,000",   "view": 2, "rec": False, "desc": "저렴한 가격으로 라이브 야구 경험"},
        ],
        "best_seats": [
            {"title": "가성비 관람", "seat": "내야 2층 중앙부", "reason": "1만원 초반 가격에 전체 경기 조망 가능."},
            {"title": "자가용 방문", "seat": "내야 1층 3루 측", "reason": "주차 후 3루 게이트 가까워 이동 편리."},
            {"title": "단체 응원",   "seat": "외야 응원석",     "reason": "위즈 응원단과 함께하면 에너지 최고!"},
        ],
    },
    "incheon": {
        "id": "incheon", "tier": "1군",
        "name": "인천SSG랜더스필드",
        "teams": "SSG 랜더스",
        "address": "인천 미추홀구 매소홀로 618",
        "subway": "인천1호선 문학경기장역 도보 5분",
        "capacity": 23000,
        "color": "#0047ab", "emoji": "🔷",
        "tip": "신세계 계열 푸드코트가 잘 되어 있어요. 경기 후 이마트 쇼핑도 가능!",
        "sections": [
            {"name": "테이블석",    "zone": "premium", "price": "60,000~",       "view": 5, "rec": True,  "desc": "F&B 포함 프리미엄 관람"},
            {"name": "내야 1층",    "zone": "inner",   "price": "14,000~18,000", "view": 5, "rec": True,  "desc": "인조잔디 위 경기 생생하게 관람"},
            {"name": "내야 2층",    "zone": "upper",   "price": "11,000~14,000", "view": 4, "rec": True,  "desc": "좌우 넓은 전체 경기장 시야"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "8,000~10,000",  "view": 3, "rec": False, "desc": "빨간 랜더스 응원의 열기"},
            {"name": "외야 일반석", "zone": "outer",   "price": "7,000~9,000",   "view": 3, "rec": False, "desc": "가성비 관람, 응원 분위기 함께"},
        ],
        "best_seats": [
            {"title": "첫 직관 추천", "seat": "내야 1층 1루 측", "reason": "경기장 잔디 냄새 맡으며 타격감 생생하게 느낄 수 있어요."},
            {"title": "여유로운 관람", "seat": "테이블석",        "reason": "신세계 F&B와 함께 편하게 관람 가능."},
            {"title": "인증샷 명소",   "seat": "내야 2층 중앙",   "reason": "SSG 랜더스필드 전경이 가장 예쁘게 나와요."},
        ],
    },
    "daegu": {
        "id": "daegu", "tier": "1군",
        "name": "대구삼성라이온즈파크",
        "teams": "삼성 라이온즈",
        "address": "대구 수성구 야구전설로 1",
        "subway": "대구지하철 2호선 대공원역",
        "capacity": 24000,
        "color": "#c8102e", "emoji": "❤️",
        "tip": "2016년 개장한 최신 시설이에요. 좌석 간격이 넓고 시야를 가리는 기둥이 없어요.",
        "sections": [
            {"name": "다이아몬드석", "zone": "premium", "price": "70,000~",       "view": 5, "rec": True,  "desc": "최고급 서비스와 최상의 시야"},
            {"name": "내야 1층",     "zone": "inner",   "price": "15,000~20,000", "view": 5, "rec": True,  "desc": "넓은 좌석 간격, 기둥 없는 완벽한 시야"},
            {"name": "내야 2층",     "zone": "upper",   "price": "12,000~15,000", "view": 4, "rec": True,  "desc": "대구 구장 전경 최고 조망"},
            {"name": "외야 응원석",  "zone": "cheer",   "price": "8,000~10,000",  "view": 3, "rec": False, "desc": "삼성 응원단의 뜨거운 응원"},
            {"name": "외야 일반석",  "zone": "outer",   "price": "7,000~9,000",   "view": 3, "rec": False, "desc": "저렴한 가격으로 야구 관람"},
        ],
        "best_seats": [
            {"title": "시야 최우선", "seat": "내야 1층 어디든", "reason": "국내에서 기둥 없는 완전 시야 확보 가능한 최신 구장."},
            {"title": "사진 명소",   "seat": "내야 2층 중앙",   "reason": "대구 구장 특유의 붉은 응원석이 장관이에요."},
            {"title": "합리적 선택", "seat": "내야 2층 1루 측", "reason": "가성비와 시야 모두 잡을 수 있는 최선의 선택."},
        ],
    },
    "busan": {
        "id": "busan", "tier": "1군",
        "name": "부산사직야구장",
        "teams": "롯데 자이언츠",
        "address": "부산 동래구 사직로 45",
        "subway": "부산지하철 3호선 사직역 1번 출구",
        "capacity": 24700,
        "color": "#1a237e", "emoji": "🔵",
        "tip": "롯데 팬들의 응원 열기가 KBO 최고 수준이에요. 외야 응원석 분위기는 정말 독보적!",
        "sections": [
            {"name": "내야 1층",    "zone": "inner",   "price": "12,000~16,000", "view": 4, "rec": True,  "desc": "부산 바닷바람 맞으며 야구 관람"},
            {"name": "내야 2층",    "zone": "upper",   "price": "10,000~13,000", "view": 4, "rec": True,  "desc": "전체 경기장 조망, 구장 특유의 옛 감성"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "7,000~9,000",   "view": 3, "rec": True,  "desc": "KBO 최고의 응원 분위기, 꼭 한 번은 경험해야!"},
            {"name": "외야 일반석", "zone": "outer",   "price": "6,000~8,000",   "view": 2, "rec": False, "desc": "저렴하지만 시야 제한 있음"},
        ],
        "best_seats": [
            {"title": "응원 경험",   "seat": "외야 응원석",   "reason": "롯데 팬들의 응원은 KBO 최고! 꼭 한 번은 경험해보세요."},
            {"title": "편안한 관람", "seat": "내야 1층 중앙", "reason": "사직 구장 특유의 클래식한 분위기와 함께."},
            {"title": "야경 관람",   "seat": "내야 2층 중앙", "reason": "야간 경기 시 부산 야경과 함께 낭만 있어요."},
        ],
    },
    "gwangju": {
        "id": "gwangju", "tier": "1군",
        "name": "광주-기아 챔피언스 필드",
        "teams": "KIA 타이거즈",
        "address": "광주 북구 서림로 10",
        "subway": "광주지하철 1호선 화정역",
        "capacity": 20500,
        "color": "#006400", "emoji": "💚",
        "tip": "KIA 팬들의 응원 열기가 대단해요. 전통 명가답게 응원 문화가 잘 발달되어 있어요.",
        "sections": [
            {"name": "프리미엄석",  "zone": "premium", "price": "50,000~",       "view": 5, "rec": True,  "desc": "최고 시야와 편의시설"},
            {"name": "내야 1층",    "zone": "inner",   "price": "13,000~16,000", "view": 5, "rec": True,  "desc": "KIA 타이거즈 홈 그라운드 생생하게"},
            {"name": "내야 2층",    "zone": "upper",   "price": "10,000~13,000", "view": 4, "rec": True,  "desc": "전체 경기 조망, 광주 구장 전경"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "7,000~9,000",   "view": 3, "rec": False, "desc": "KIA 응원단과 함께하는 뜨거운 응원"},
            {"name": "외야 일반석", "zone": "outer",   "price": "6,000~8,000",   "view": 2, "rec": False, "desc": "저렴한 가격, 분위기는 뜨겁게"},
        ],
        "best_seats": [
            {"title": "KIA 팬이라면",  "seat": "외야 응원석",     "reason": "광주 팬들의 응원 열기가 정말 남달라요."},
            {"title": "시야 + 가성비", "seat": "내야 2층 1루 측", "reason": "1만원 초반대로 전체 경기 시야 확보 가능."},
            {"title": "특별한 날",     "seat": "프리미엄석",      "reason": "기념일, 생일에 특별한 야구 관람 경험."},
        ],
    },
    "daejeon": {
        "id": "daejeon", "tier": "1군",
        "name": "한화생명이글스파크",
        "teams": "한화 이글스",
        "address": "대전 중구 대종로 373",
        "subway": "대전 시내버스 이용 권장",
        "capacity": 13000,
        "color": "#ff6b00", "emoji": "🟧",
        "tip": "소규모 구장이라 어디서든 선수가 가까워요. 한화 팬들의 열정은 KBO 최고 수준!",
        "sections": [
            {"name": "내야 1층",    "zone": "inner",   "price": "12,000~15,000", "view": 5, "rec": True,  "desc": "선수와 가장 가까운 거리, 생생한 현장감"},
            {"name": "내야 2층",    "zone": "upper",   "price": "9,000~12,000",  "view": 4, "rec": True,  "desc": "소규모 구장이라 2층도 가까운 느낌"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "7,000~8,000",   "view": 3, "rec": True,  "desc": "한화 이글스 응원 분위기 최고"},
            {"name": "외야 일반석", "zone": "outer",   "price": "5,000~7,000",   "view": 2, "rec": False, "desc": "최저가로 야구 관람 가능"},
        ],
        "best_seats": [
            {"title": "선수 가까이", "seat": "내야 1층 어디든", "reason": "소규모 구장이라 어디서든 선수가 바로 옆에 있는 느낌."},
            {"title": "응원 경험",   "seat": "외야 응원석",     "reason": "한화 팬들의 열정은 KBO 최고라 꼭 경험해봐야 해요."},
            {"title": "가성비",      "seat": "내야 2층 중앙",   "reason": "9천원에 최고의 야구 관람 경험 가능."},
        ],
    },
    "changwon": {
        "id": "changwon", "tier": "1군",
        "name": "창원NC파크",
        "teams": "NC 다이노스",
        "address": "경남 창원시 마산회원구 삼호로 63",
        "subway": "창원버스터미널에서 버스 이용",
        "capacity": 22000,
        "color": "#00008b", "emoji": "💙",
        "tip": "2019년 개장한 최신 구장이에요. 공룡 테마 인테리어가 독특하고 편의시설이 매우 뛰어나요.",
        "sections": [
            {"name": "다이노스석",  "zone": "premium", "price": "60,000~",       "view": 5, "rec": True,  "desc": "공룡 테마 최고급 좌석"},
            {"name": "내야 1층",    "zone": "inner",   "price": "14,000~18,000", "view": 5, "rec": True,  "desc": "최신 시설 기둥 없는 완벽한 시야"},
            {"name": "내야 2층",    "zone": "upper",   "price": "11,000~14,000", "view": 4, "rec": True,  "desc": "NC파크 전경, 마산만 풍경도 보임"},
            {"name": "외야 응원석", "zone": "cheer",   "price": "8,000~10,000",  "view": 3, "rec": False, "desc": "공룡 응원 문화 체험"},
            {"name": "외야 일반석", "zone": "outer",   "price": "7,000~9,000",   "view": 3, "rec": False, "desc": "저렴한 가격, 분위기 있는 관람"},
        ],
        "best_seats": [
            {"title": "최신 시설 만끽", "seat": "내야 1층 중앙",  "reason": "2019년 개장 최신 구장 시설을 가장 잘 느낄 수 있어요."},
            {"title": "야경 + 바다뷰",  "seat": "내야 2층 중앙",  "reason": "야간 경기 시 마산만 야경과 함께 낭만 있어요."},
            {"title": "공룡 테마 체험", "seat": "다이노스석",      "reason": "NC파크만의 특별한 공룡 테마 경험."},
        ],
    },

    # ── 2군 구장 (퓨처스리그) ────────────────────────────────────
    "ulsan": {
        "id": "ulsan", "tier": "2군",
        "name": "울산문수야구장",
        "teams": "롯데 자이언츠 2군",
        "address": "울산 남구 문수로 44",
        "subway": "울산 시내버스 이용",
        "capacity": 12000,
        "color": "#4b0082", "emoji": "💜",
        "tip": "롯데 자이언츠 2군(퓨처스)의 홈구장이에요. 미래의 롯데 스타를 가장 먼저 만날 수 있어요.",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000",  "view": 4, "rec": True,  "desc": "소규모 구장, 선수 바로 옆 느낌"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000",  "view": 3, "rec": False, "desc": "저렴하게 퓨처스 야구 관람"},
        ],
        "best_seats": [
            {"title": "유망주 직관", "seat": "내야석 1루 측", "reason": "소규모 구장이라 선수 표정까지 보여요."},
            {"title": "가성비",      "seat": "내야석 어디든", "reason": "5천원 내외로 최고의 현장감 가능."},
        ],
    },
    "icheon_lg": {
        "id": "icheon_lg", "tier": "2군",
        "name": "이천LG챔피언스파크",
        "teams": "LG 트윈스 2군",
        "address": "경기 이천시 이섭대천로 413",
        "subway": "버스 이용 (이천터미널 하차 후 택시)",
        "capacity": 3000,
        "color": "#c8032c", "emoji": "🔴",
        "tip": "LG의 유망주 육성 전용 시설이에요. 퓨처스리그에서 미래의 LG 스타를 먼저 만나보세요.",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000", "view": 4, "rec": True,  "desc": "소규모 구장 특유의 가까운 관람"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000", "view": 3, "rec": False, "desc": "저렴하게 유망주 직관"},
        ],
        "best_seats": [
            {"title": "유망주 발굴", "seat": "내야석 홈플레이트 근처", "reason": "LG 1군 콜업 예정 선수들을 가장 가까이서 볼 수 있어요."},
            {"title": "여유로운 관람", "seat": "내야석 어디든",         "reason": "관중이 적어 여유롭고 편안하게 야구 즐기기 좋아요."},
        ],
    },
    "icheon_doosan": {
        "id": "icheon_doosan", "tier": "2군",
        "name": "이천두산베어스파크",
        "teams": "두산 베어스 2군",
        "address": "경기 이천시 마장면 덕이로 228",
        "subway": "버스 이용 (이천터미널 하차 후 이동)",
        "capacity": 3000,
        "color": "#131230", "emoji": "🐻",
        "tip": "두산의 2군 전용 훈련·경기 시설이에요. 베어스의 미래 자원들을 먼저 만날 수 있는 곳!",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000", "view": 4, "rec": True,  "desc": "조용하고 여유로운 퓨처스 관람"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000", "view": 3, "rec": False, "desc": "가성비 최고의 야구 관람"},
        ],
        "best_seats": [
            {"title": "유망주 스카우팅", "seat": "내야석 중앙",  "reason": "두산의 1군 콜업 후보들을 미리 체크할 수 있어요."},
            {"title": "조용한 직관",     "seat": "내야석 어디든", "reason": "북적이지 않아 야구에 집중하기 딱 좋아요."},
        ],
    },
    "gyeongsan": {
        "id": "gyeongsan", "tier": "2군",
        "name": "경산삼성라이온즈파크",
        "teams": "삼성 라이온즈 2군",
        "address": "경북 경산시 삼성로 100",
        "subway": "대구지하철 2호선 경산역 → 버스 이동",
        "capacity": 5000,
        "color": "#074ca1", "emoji": "🦁",
        "tip": "삼성 라이온즈 2군의 전용 홈구장이에요. 대구 삼성파크보다 아담하고 편안한 분위기예요.",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000", "view": 4, "rec": True,  "desc": "아담한 구장에서 선수 가까이 관람"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000", "view": 3, "rec": False, "desc": "저렴한 퓨처스 야구 관람"},
        ],
        "best_seats": [
            {"title": "삼성 유망주 직관", "seat": "내야석 1루 측",  "reason": "미래의 삼성 라이온즈 주전을 가장 먼저 만날 수 있어요."},
            {"title": "가성비 직관",      "seat": "내야석 어디든", "reason": "저렴한 가격에 야구의 본질을 느낄 수 있어요."},
        ],
    },
    "cheongju": {
        "id": "cheongju", "tier": "2군",
        "name": "청주한화생명이글스파크",
        "teams": "한화 이글스 2군",
        "address": "충북 청주시 청원구 오창읍 양청리",
        "subway": "청주 시내버스 이용",
        "capacity": 5000,
        "color": "#ff6b00", "emoji": "🦅",
        "tip": "한화 이글스 2군의 홈구장이에요. 이글스 팬이라면 대전에 이어 청주도 방문해보세요!",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000", "view": 4, "rec": True,  "desc": "아담한 구장에서 한화 유망주 관람"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000", "view": 3, "rec": False, "desc": "저렴한 퓨처스 야구 관람"},
        ],
        "best_seats": [
            {"title": "이글스 팬 성지", "seat": "내야석 중앙",   "reason": "한화의 미래를 책임질 유망주들을 가장 가까이서 볼 수 있어요."},
            {"title": "조용한 직관",    "seat": "내야석 어디든", "reason": "대전 이글스파크보다 훨씬 조용하고 여유로워요."},
        ],
    },
    "goyang": {
        "id": "goyang", "tier": "2군",
        "name": "고양키움히어로즈파크",
        "teams": "키움 히어로즈 2군",
        "address": "경기 고양시 덕양구 고양대로 1234",
        "subway": "3호선 원흥역 → 버스 이동",
        "capacity": 4000,
        "color": "#cc0000", "emoji": "⚡",
        "tip": "키움 히어로즈 2군의 홈구장이에요. 고척돔에 가기 전 유망주들을 여기서 먼저 만나보세요!",
        "sections": [
            {"name": "내야석", "zone": "inner", "price": "5,000~8,000", "view": 4, "rec": True,  "desc": "소규모 구장에서 유망주 가까이 관람"},
            {"name": "외야석", "zone": "outer", "price": "3,000~5,000", "view": 3, "rec": False, "desc": "저렴한 퓨처스 야구 관람"},
        ],
        "best_seats": [
            {"title": "히어로즈 팬 필수", "seat": "내야석 홈플레이트 근처", "reason": "키움의 미래 에이스·거포를 가장 먼저 만나볼 수 있어요."},
            {"title": "여유로운 직관",    "seat": "내야석 어디든",          "reason": "관중이 적어 경기 집중도 최고, 선수와 거리도 가까워요."},
        ],
    },
}
